name: Publish Ray Jobs Plugin

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "plugins/hydra_ray_jobs_launcher/**"

jobs:
  ray_jobs_plugin_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: cd plugins/hydra_ray_jobs_launcher && python -m build

      - name: Publish to Test PyPI
        continue-on-error: true
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          cd plugins/hydra_ray_jobs_launcher && python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd plugins/hydra_ray_jobs_launcher && python -m twine upload dist/*
